defaults:
  - _self_
  - algorithm: ppo_baseline
  - search_space: ${algorithm}
  - override hydra/sweeper: DEHB

hydra:
  sweeper:
    dehb_kwargs:
      mutation_factor: 0.2
      max_budget: ${algorithm.total_timesteps}
      min_budget: 2e3
      deepcave: False
    search_space: ${search_space}
    total_brackets: 3
    budget_variable: algorithm.total_timesteps
  run:
    dir: ./tmp/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./tmp/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job_logging:
    level: _

run_name: _
run_time: _
env:
  name: ant
  framework: brax
  backend: generalized
  num_envs: 64
  num_envs_for_eval: 32
  noise_lvl: 0.05
  action_size: _
  observation_size: _
  dt: _
  merton:
    dt: 0.02
    horizon: 1.0
    mu: 0.08
    sigma: 0.2
    risk_free_rate: 0.02
    initial_wealth: 1.0
    action_limit: 2.0

load: false
save: false
reward_curves: false
seed: 0
